<?php
// TAG Protect - FreePBX module (BMO class).
// License: GPLv3+
#[\AllowDynamicProperties]
class Tagprotect extends \FreePBX_Helpers implements \BMO {

	const SCREEN   = 'tag-inbound-screen,s,1';
	const KV_CD    = 'kvstore_FreePBX_modules_Customappsreg';   // FreePBX Custom Destinations store
	const ETC      = '/etc/asterisk';
	const AGI_DST  = '/var/lib/asterisk/agi-bin/tag-check.php';
	const SOUNDDIR = '/var/lib/asterisk/sounds/en/custom';
	const CACHEDIR = '/var/lib/asterisk/tagprotect';

	public function __construct($freepbx = null) {
		if ($freepbx === null) throw new \Exception('Not given a FreePBX Object');
		$this->FreePBX = $freepbx;
		$this->db = $freepbx->Database;
	}

	// ---- defaults ----
	public function defaults() {
		return array(
			'enabled'    => '1',
			'outbound'   => '1',
			'base_url'   => 'https://callblocker.overcloud.us/api/v1',
			'api_key'    => '',
			'requester'  => 'pbx',
			'lists'      => 'all',
			'timeout_ms' => '1500',
			'cache_ttl'  => '86400',
			'allow_url'  => 'https://raw.githubusercontent.com/Shwerzb/tag-protect-freepbx/main/always-allow.txt',
		);
	}
	public function get($k) {
		$v = $this->getConfig($k);
		if ($v === false || $v === null || $v === '') { $d = $this->defaults(); return isset($d[$k]) ? $d[$k] : ''; }
		return $v;
	}

	// ---- BMO lifecycle ----
	public function install() {
		// Migration: if a script-based /etc/asterisk/tagprotect.conf already exists,
		// import its settings so installing the module doesn't blank a working setup.
		if (empty($this->getConfig('api_key'))) {
			$conf = self::ETC.'/tagprotect.conf';
			if (file_exists($conf)) {
				$ini = @parse_ini_file($conf);
				foreach (array('api_key','base_url','requester','lists','timeout_ms','cache_ttl') as $k)
					if (!empty($ini[$k])) $this->setConfig($k, $ini[$k]);
				$this->setConfig('enabled','1'); $this->setConfig('outbound','1');
			}
		}
		$this->installFiles();
		// seed always-allow list from the bundled file if none present yet
		$active = self::ETC.'/tagprotect-emergency.txt';
		if (!file_exists($active) && file_exists(__DIR__.'/always-allow.txt')) {
			@copy(__DIR__.'/always-allow.txt', $active);
			@chown($active, 'asterisk'); @chgrp($active, 'asterisk');
		}
		$local = self::ETC.'/tagprotect-emergency.local.txt';
		if (!file_exists($local)) { @touch($local); @chown($local,'asterisk'); @chgrp($local,'asterisk'); }
		$this->writeConfFile();
	}
	public function uninstall() {
		// restore any screened inbound routes, then drop our dialplan on next reload
		foreach ($this->routes() as $r) if ($r['screened']) $this->unwireRoute($r['extension'], $r['cidnum']);
	}
	public function backup() {}
	public function restore($backup) {}
	public function doConfigPageInit($page) {}

	// ---- file install ----
	public function installFiles() {
		if (!is_dir(self::CACHEDIR)) { @mkdir(self::CACHEDIR, 0750, true); }
		@chown(self::CACHEDIR,'asterisk'); @chgrp(self::CACHEDIR,'asterisk');
		if (file_exists(__DIR__.'/agi-bin/tag-check.php')) {
			@copy(__DIR__.'/agi-bin/tag-check.php', self::AGI_DST);
			@chmod(self::AGI_DST, 0750); @chown(self::AGI_DST,'asterisk'); @chgrp(self::AGI_DST,'asterisk');
		}
		if (!is_dir(self::SOUNDDIR)) { @mkdir(self::SOUNDDIR, 0775, true); }
		$src = __DIR__.'/sounds/tag-blocked.wav';
		if (file_exists($src)) {
			$sox = trim(shell_exec('command -v sox 2>/dev/null'));
			if ($sox) {
				exec("sox ".escapeshellarg($src)." -r 8000 -c 1 -b 16 ".escapeshellarg(self::SOUNDDIR.'/tag-blocked.wav')." 2>/dev/null");
				exec("sox ".escapeshellarg($src)." -r 8000 -c 1 -t ul ".escapeshellarg(self::SOUNDDIR.'/tag-blocked.ulaw')." 2>/dev/null");
			} else { @copy($src, self::SOUNDDIR.'/tag-blocked.wav'); }
			@chown(self::SOUNDDIR.'/tag-blocked.wav','asterisk'); @chgrp(self::SOUNDDIR.'/tag-blocked.wav','asterisk');
		}
	}

	// ---- write /etc/asterisk/tagprotect.conf from settings ----
	public function writeConfFile() {
		$c  = "; Generated by the TAG Protect FreePBX module - do not edit by hand\n";
		$c .= "api_key    = ".$this->get('api_key')."\n";
		$c .= "base_url   = ".$this->get('base_url')."\n";
		$c .= "requester  = ".$this->get('requester')."\n";
		$c .= "lists      = ".$this->get('lists')."\n";
		$c .= "timeout_ms = ".$this->get('timeout_ms')."\n";
		$c .= "cache_ttl  = ".$this->get('cache_ttl')."\n";
		$c .= "cache_db   = ".self::CACHEDIR."/cache.db\n";
		@file_put_contents(self::ETC.'/tagprotect.conf', $c);
		@chmod(self::ETC.'/tagprotect.conf', 0640); @chown(self::ETC.'/tagprotect.conf','asterisk'); @chgrp(self::ETC.'/tagprotect.conf','asterisk');
	}

	// ---- always-allow editor ----
	public function readAllow() {
		$f = self::ETC.'/tagprotect-emergency.txt';
		return file_exists($f) ? file_get_contents($f) : '';
	}
	public function writeAllow($text) {
		$f = self::ETC.'/tagprotect-emergency.txt';
		@file_put_contents($f, str_replace("\r\n", "\n", $text));
		@chmod($f,0644); @chown($f,'asterisk'); @chgrp($f,'asterisk');
	}
	// Pull the shared always-allow list from GitHub (or any URL) and save it.
	public function resyncAllow() {
		$url = $this->get('allow_url');
		if (empty($url)) return array(false, _("No resync URL configured."));
		$ch = curl_init($url);
		curl_setopt_array($ch, array(CURLOPT_RETURNTRANSFER=>true, CURLOPT_TIMEOUT=>15, CURLOPT_FOLLOWLOCATION=>true,
			CURLOPT_USERAGENT=>'tagprotect-module'));
		$body = curl_exec($ch); $code = curl_getinfo($ch, CURLINFO_HTTP_CODE); curl_close($ch);
		if ($body === false || $code < 200 || $code >= 300 || trim($body) === '')
			return array(false, sprintf(_("Resync failed (HTTP %s)."), $code));
		$this->writeAllow($body);
		$n = count(array_filter(array_map('trim', explode("\n", $body)), function($l){ return $l!=='' && $l[0]!=='#'; }));
		return array(true, sprintf(_("Resynced %d numbers from %s"), $n, $url));
	}

	// ---- TAG API helpers ----
	private function api($method, $path, $body = null) {
		$ch = curl_init($this->get('base_url').$path);
		$h  = array('Accept: application/json', 'X-API-Key: '.$this->get('api_key'));
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
		curl_setopt($ch, CURLOPT_TIMEOUT, 12);
		if ($body !== null) { curl_setopt($ch, CURLOPT_POST, true); curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($body)); $h[] = 'Content-Type: application/json'; }
		curl_setopt($ch, CURLOPT_HTTPHEADER, $h);
		$r = curl_exec($ch); $code = curl_getinfo($ch, CURLINFO_HTTP_CODE); curl_close($ch);
		return array('code'=>$code, 'json'=>json_decode($r, true), 'raw'=>$r);
	}
	public function fetchLists() {
		$r = $this->api('GET', '/lists');
		if (!empty($r['json']['data']['lists'])) return $r['json']['data']['lists'];
		return array();
	}
	public function testNumber($num) {
		$r = $this->api('POST', '/lists/check', array('number'=>$num, 'lists'=>array($this->get('lists')), 'requester'=>$this->get('requester')));
		return isset($r['json']['data']) ? $r['json']['data'] : array('status'=>'error','message'=>($r['json']['error']['message'] ?? 'request failed'));
	}

	// ---- inbound routes / wiring (via FreePBX Custom Destinations kvstore) ----
	private function cdLoad() {
		$out = array();
		try { $rows = $this->db->query("SELECT `key`,`val` FROM `".self::KV_CD."` WHERE `id`='dests'")->fetchAll(\PDO::FETCH_ASSOC); }
		catch (\Exception $e) { return $out; }
		foreach ($rows as $r) $out[$r['key']] = json_decode($r['val'], true);
		return $out;
	}
	private function cdNextId($d) { $m=0; foreach (array_keys($d) as $k) if (is_numeric($k) && (int)$k>$m) $m=(int)$k; return $m+1; }
	private function cdAdd($dest, $desc) {
		$d = $this->cdLoad();
		foreach ($d as $id=>$v) if (($v['target']??'')===self::SCREEN && ($v['dest']??'')===$dest) return $id;
		$id = $this->cdNextId($d);
		$json = json_encode(array('destid'=>(string)$id,'target'=>self::SCREEN,'description'=>$desc,'notes'=>'','destret'=>'1','dest'=>$dest));
		$st = $this->db->prepare("INSERT INTO `".self::KV_CD."` (`key`,`val`,`type`,`id`) VALUES (?,?,'json-arr','dests')");
		$st->execute(array((string)$id,$json));
		return $id;
	}
	private function screenedId($destination, $d) {
		if (preg_match('/^customdests,dest-(\d+),1$/', $destination, $m) && isset($d[$m[1]]) && ($d[$m[1]]['target']??'')===self::SCREEN) return $m[1];
		return false;
	}
	public function routes() {
		$d = $this->cdLoad();
		$out = array();
		$rows = $this->db->query("SELECT extension,cidnum,destination,description FROM incoming")->fetchAll(\PDO::FETCH_ASSOC);
		foreach ($rows as $r) {
			$sid = $this->screenedId($r['destination'], $d);
			$out[] = array(
				'extension'=>$r['extension'], 'cidnum'=>$r['cidnum'],
				'description'=>$r['description'], 'destination'=>$r['destination'],
				'screened'=>($sid!==false), 'orig'=>($sid!==false ? ($d[$sid]['dest']??'') : $r['destination']),
				'key'=>$r['extension'].'|'.$r['cidnum'],
			);
		}
		return $out;
	}
	public function wireRoute($ext, $cid) {
		$d = $this->cdLoad();
		$row = $this->db->query("SELECT destination FROM incoming WHERE extension=".$this->db->quote($ext)." AND COALESCE(cidnum,'')=COALESCE(".$this->db->quote($cid).",'')")->fetch(\PDO::FETCH_ASSOC);
		if (!$row) return;
		if ($this->screenedId($row['destination'], $d)!==false) return;
		$id = $this->cdAdd($row['destination'], 'TAG screen -> '.$row['destination']);
		$st = $this->db->prepare("UPDATE incoming SET destination=? WHERE extension=? AND COALESCE(cidnum,'')=COALESCE(?,'')");
		$st->execute(array("customdests,dest-$id,1", $ext, $cid));
	}
	public function unwireRoute($ext, $cid) {
		$d = $this->cdLoad();
		$row = $this->db->query("SELECT destination FROM incoming WHERE extension=".$this->db->quote($ext)." AND COALESCE(cidnum,'')=COALESCE(".$this->db->quote($cid).",'')")->fetch(\PDO::FETCH_ASSOC);
		if (!$row) return;
		$sid = $this->screenedId($row['destination'], $d);
		if ($sid===false) return;
		$orig = $d[$sid]['dest'] ?? 'app-blackhole,hangup,1';
		$st = $this->db->prepare("UPDATE incoming SET destination=? WHERE extension=? AND COALESCE(cidnum,'')=COALESCE(?,'')");
		$st->execute(array($orig, $ext, $cid));
	}

	// ---- dialplan (called from functions.inc.php) ----
	public function genDialplan(&$ext) {
		if ($this->get('enabled') !== '1') return;
		// outbound predial hook
		if ($this->get('outbound') === '1') {
			$c = 'macro-dialout-trunk-predial-hook';
			$ext->add($c, 's', '', new \ext_agi('tag-check.php,out,${OUTNUM}'));
			$ext->add($c, 's', '', new \ext_gotoif('$["${TAGPROTECT_BLOCKED}"="1"]', 'tag-blocked,s,1'));
			$ext->add($c, 's', '', new \ext_return(''));
		}
		// inbound screen context (custom destinations point here)
		$ci = 'tag-inbound-screen';
		$ext->add($ci, 's', '', new \ext_agi('tag-check.php,in,${CALLERID(num)}'));
		$ext->add($ci, 's', '', new \ext_gotoif('$["${TAGPROTECT_BLOCKED}"="1"]', 'tag-blocked,s,1'));
		$ext->add($ci, 's', '', new \ext_return(''));
		// blocked handler
		$cb = 'tag-blocked';
		$ext->add($cb, 's', '', new \ext_noop('TAG Protect blocked ${CALLERID(num)} -> ${OUTNUM}'));
		$ext->add($cb, 's', '', new \ext_answer(''));
		$ext->add($cb, 's', '', new \ext_wait('1'));
		$ext->add($cb, 's', '', new \ext_playback('custom/tag-blocked'));
		$ext->add($cb, 's', '', new \ext_hangup(''));
	}

	// ---- toolbar ----
	public function getActionBar($request) {
		if (($_GET['display'] ?? '') !== 'tagprotect') return array();
		return array(
			'submit' => array('name'=>'submit', 'id'=>'submit', 'value'=>_("Submit")),
			'reset'  => array('name'=>'reset',  'id'=>'reset',  'value'=>_("Reset")),
		);
	}
}
