#!/usr/bin/env bash
# TAG Protect - main setup (invoked by install.sh after the repo is downloaded).
# Usage: bash lib/setup.sh <repo_dir>
set -euo pipefail

REPODIR="${1:-$(cd "$(dirname "$0")/.." && pwd)}"
API_BASE_DEFAULT="https://callblocker.overcloud.us/api/v1"
AGI=/var/lib/asterisk/agi-bin
ETC=/etc/asterisk
SOUNDS=/var/lib/asterisk/sounds/en/custom
CACHE_DIR=/var/lib/asterisk/tagprotect
EXT=$ETC/extensions_custom.conf
BIN=/usr/local/bin/tagprotect
MARK="; === TAG-PROTECT (managed by addon) ==="
TTY=/dev/tty

g(){ printf '\033[32m%s\033[0m\n' "$*"; }
y(){ printf '\033[33m%s\033[0m\n' "$*"; }
r(){ printf '\033[31m%s\033[0m\n' "$*"; }
die(){ r "ERROR: $*"; exit 1; }
ask(){ local p="$1" d="${2:-}" a=""; if [ -n "$d" ]; then printf '%s [%s]: ' "$p" "$d" >"$TTY"; else printf '%s: ' "$p" >"$TTY"; fi; read -r a <"$TTY" || true; echo "${a:-$d}"; }
yesno(){ local a; a="$(ask "$1 (y/n)" "${2:-y}")"; case "$a" in y|Y|yes|YES) return 0;; *) return 1;; esac; }

g "=========================================="
g "  TAG Protect for FreePBX - setup"
g "=========================================="
[ "$(id -u)" -eq 0 ] || die "Run as root."
command -v asterisk >/dev/null || die "Asterisk not found - this must run on a FreePBX/Asterisk server."
command -v php >/dev/null || die "php CLI not found."
php -m | grep -qi '^curl$'    || die "php-curl is required."
php -m | grep -qi '^sqlite3$' || y "  note: php-sqlite3 missing -> caching disabled (still works, just more API calls)."
command -v fwconsole >/dev/null || y "  note: fwconsole not found - will use 'asterisk -rx' to reload."

# ---- settings ----
API_BASE="$(ask 'API base URL' "$API_BASE_DEFAULT")"
while :; do
  APIKEY="$(ask 'TAG Protect API key (cbk_...)')"
  [ -n "$APIKEY" ] || { r "  key required"; continue; }
  y "  validating key ..."
  RESP="$(curl -s --max-time 12 -H "X-API-Key: $APIKEY" -H 'Accept: application/json' "$API_BASE/lists" || true)"
  if echo "$RESP" | grep -q '"slug"'; then
    g "  key OK - lists on this account:"
    echo "$RESP" | grep -oE '"slug":"[^"]*"' | sed 's/"slug":"/    - /; s/"//' >"$TTY"
    break
  fi
  r "  rejected: $(echo "$RESP" | grep -oE '"message":"[^"]*"' | head -1) (keys are case-sensitive)"
done
LISTS="$(ask 'Lists to enforce (all, or comma-separated slugs)' 'all')"
REQUESTER="$(ask 'Billing/location ID (UNIQUE per site - $20/mo each)')"
[ -n "$REQUESTER" ] || die "requester is required."
CACHE_TTL="$(ask 'Cache lifetime in seconds (86400 = 24h)' '86400')"
TIMEOUT_MS="$(ask 'API timeout ms (fail-open if exceeded)' '1500')"

# ---- files ----
mkdir -p "$AGI" "$CACHE_DIR" "$SOUNDS"
install -o asterisk -g asterisk -m 0750 "$REPODIR/tag-check.php" "$AGI/tag-check.php"
sed -i 's/\r$//' "$AGI/tag-check.php"   # defensive: ensure LF even on odd checkouts
php -l "$AGI/tag-check.php" >/dev/null || die "tag-check.php failed to lint"
install -o asterisk -g asterisk -m 0644 "$REPODIR/always-allow.txt" "$ETC/tagprotect-emergency.txt"
sed -i 's/\r$//' "$ETC/tagprotect-emergency.txt"
[ -f "$ETC/tagprotect-emergency.local.txt" ] || install -o asterisk -g asterisk -m 0644 /dev/null "$ETC/tagprotect-emergency.local.txt"
g "  installed AGI + always-allow list"

cat >"$ETC/tagprotect.conf" <<CFG
; TAG Protect config - generated by setup
api_key    = $APIKEY
base_url   = $API_BASE
requester  = $REQUESTER
lists      = $LISTS
timeout_ms = $TIMEOUT_MS
cache_ttl  = $CACHE_TTL
cache_db   = $CACHE_DIR/cache.db
CFG
chown asterisk:asterisk "$ETC/tagprotect.conf"; chmod 0640 "$ETC/tagprotect.conf"
chown asterisk:asterisk "$CACHE_DIR"; chmod 0750 "$CACHE_DIR"
g "  wrote $ETC/tagprotect.conf"

# ---- dialplan ----
if grep -qF "$MARK" "$EXT" 2>/dev/null; then
  y "  dialplan already present"
elif grep -q '^\[macro-dialout-trunk-predial-hook\]' "$EXT" 2>/dev/null; then
  y "  !! existing predial hook found - merge the AGI lines manually (see README)"
else
  cat >>"$EXT" <<'DP'

; === TAG-PROTECT (managed by addon) ===
[macro-dialout-trunk-predial-hook]
exten => s,1,AGI(tag-check.php,out,${OUTNUM})
 same => n,ExecIf($["${TAGPROTECT_BLOCKED}"="1"]?Goto(tag-blocked,s,1))
 same => n,Return()

[tag-inbound-screen]
exten => s,1,AGI(tag-check.php,in,${CALLERID(num)})
 same => n,ExecIf($["${TAGPROTECT_BLOCKED}"="1"]?Goto(tag-blocked,s,1))
 same => n,Return()

[tag-blocked]
exten => s,1,NoOp(TAG Protect blocked ${CALLERID(num)} -> ${OUTNUM})
 same => n,Answer()
 same => n,Wait(1)
 same => n,Playback(custom/tag-blocked)
 same => n,Hangup()
DP
  g "  added dialplan (outbound hook + inbound context + blocked handler)"
fi

# ---- recording ----
if [ -f "$REPODIR/sounds/tag-blocked.wav" ]; then
  if command -v sox >/dev/null; then
    sox "$REPODIR/sounds/tag-blocked.wav" -r 8000 -c 1 -b 16 "$SOUNDS/tag-blocked.wav"
    sox "$REPODIR/sounds/tag-blocked.wav" -r 8000 -c 1 -t ul "$SOUNDS/tag-blocked.ulaw"
  else cp "$REPODIR/sounds/tag-blocked.wav" "$SOUNDS/tag-blocked.wav"; fi
  chown asterisk:asterisk "$SOUNDS"/tag-blocked.* ; chmod 644 "$SOUNDS"/tag-blocked.*
  g "  installed block-message recording"
fi

# ---- CLI ----
install -m 0755 "$REPODIR/bin/tagprotect" "$BIN"
g "  installed 'tagprotect' command"

# ---- reload ----
g "==> reloading ..."
if command -v fwconsole >/dev/null; then fwconsole reload >/dev/null 2>&1 || asterisk -rx "dialplan reload" >/dev/null; else asterisk -rx "dialplan reload" >/dev/null; fi

# ---- inbound wiring ----
g "==> INBOUND routes:"
php "$REPODIR/lib/wire-inbound.php" status >"$TTY" 2>&1 || true
if yesno "Route ALL inbound calls through TAG screening now?" "y"; then
  php "$REPODIR/lib/wire-inbound.php" wire >"$TTY" 2>&1
  if command -v fwconsole >/dev/null; then fwconsole reload >/dev/null 2>&1; else asterisk -rx "dialplan reload" >/dev/null; fi
  g "  inbound wired + reloaded"
else
  y "  skipped inbound (run 'tagprotect wire-in' later)"
fi

# ---- self test ----
g "==> self-test:"
T="$(curl -s --max-time 8 -X POST "$API_BASE/lists/check" -H "X-API-Key: $APIKEY" -H 'Content-Type: application/json' -d "{\"number\":\"18005551234\",\"lists\":[\"all\"],\"requester\":\"$REQUESTER\"}" || true)"
echo "  test number 18005551234 -> $(echo "$T" | grep -oE '"status":"[^"]*"' | head -1)" >"$TTY"

cat >"$TTY" <<DONE

$(g '==> DONE. Outbound + inbound blocking are live.')
  Manage it with the 'tagprotect' command:
     tagprotect status      show config, routes, cache size
     tagprotect test <num>  check a number against TAG
     tagprotect resync      pull latest always-allow list from GitHub + reload
     tagprotect allow <num> add a number to the local always-allow list
     tagprotect update      update the whole addon from GitHub
     tagprotect uninstall   remove screening (restores inbound routes)

  Config: $ETC/tagprotect.conf
DONE
